/*静态数据存储*/

/*我的图片*/
var data_myPhotos = [
	{
		'id':'indexRollImg',
		'url':'./images/photos/indexRollImg/',
		'title':'',
		'type':'',
		'photos':[
			{'imgName':'1.jpg','title':'','description':'','width':'','height':''},
			{'imgName':'2.jpg','title':'','description':'','width':'','height':''},
			{'imgName':'3.jpg','title':'','description':'','width':'','height':''},
			{'imgName':'4.jpg','title':'','description':'','width':'','height':''},
			{'imgName':'5.jpg','title':'','description':'','width':'','height':''}
		]
	},
	{
		'id':'gallery',
		'url':'./images/photos/gallery/',
		'title':'',
		'type':'',
		'photos':[
			{'imgName':'1.jpg','title':'','description':'hello','width':'','height':''},
			{'imgName':'2.jpg','title':'','description':'world','width':'','height':''},
			{'imgName':'3.jpg','title':'','description':'and','width':'','height':''},
			{'imgName':'4.jpg','title':'','description':'html5','width':'','height':''},
			{'imgName':'5.jpg','title':'','description':'css3','width':'','height':''},
			{'imgName':'1.jpg','title':'','description':'hello','width':'','height':''},
			{'imgName':'2.jpg','title':'','description':'world','width':'','height':''},
			{'imgName':'3.jpg','title':'','description':'and','width':'','height':''},
			{'imgName':'4.jpg','title':'','description':'html5','width':'','height':''},
			{'imgName':'5.jpg','title':'','description':'css3','width':'','height':''}
		]
	}
];