var data_photos = [
	{
		"id":"indexBGImg",
		"url":"./images/indexBGImg/",
		"photos":[
			{"imgName":"1.jpg","title":"","description":"","width":"1920","height":"1280"},
			{"imgName":"2.jpg","title":"","description":"","width":"1920","height":"1280"},
			{"imgName":"3.jpg","title":"","description":"","width":"1920","height":"1280"},
			{"imgName":"4.jpg","title":"","description":"","width":"1920","height":"1280"}
		]
	},
	{
		"id":"gallery",
		"url":"./images/gallery/",
		"photos":[
			{"imgName":"moon.jpg","title":"","description":"","width":"942","height":"681","rate":""},
			{"imgName":"巴拉巴拉会不会是穿越时空的符文.jpg","title":"","description":"巴拉巴拉会不会是穿越时空的符文","width":"1920","height":"1280","rate":""},
			{"imgName":"大自然的渐变色.jpg","title":"","description":"","width":"1920","height":"510","rate":""},
			{"imgName":"第一次骑骆驼.jpg","title":"","description":"","width":"1920","height":"1280","rate":""},
			{"imgName":"对于这种难得的机会在新郎没发现前蹭拍完赶紧闪啊哈哈.jpg","title":"","description":"","width":"1919","height":"982","rate":""},
			{"imgName":"和大伙伴们在扎尕那.jpg","title":"","description":"","width":"960","height":"1440","rate":""},
			{"imgName":"黄龙一景怎翠绿了得.jpg","title":"","description":"","width":"1920","height":"1280","rate":""},
			{"imgName":"经我和司机鉴定前面那辆车貌似出西西了.jpg","title":"","description":"","width":"1920","height":"1117","rate":""},
			{"imgName":"老板来一打雪糕不谢.jpg","title":"","description":"老板来一打雪糕不谢","width":"1920","height":"1280","rate":""},
			{"imgName":"你有藏獒我有相机咔.jpg","title":"","description":"","width":"576","height":"960","rate":""},
			{"imgName":"日落后的云涌.jpg","title":"","description":"","width":"1920","height":"1251","rate":""},
			{"imgName":"沙漠的线条.jpg","title":"","description":"","width":"640","height":"960","rate":""},
			{"imgName":"喂说你们呐前面那对留个联系方式回头照片传你们.jpg","title":"","description":"","width":"1920","height":"1280","rate":""},
			{"imgName":"我是属马滴.jpg","title":"","description":"","width":"1920","height":"834","rate":""},
			{"imgName":"咱也正儿八经见过日出了.jpg","title":"","description":"","width":"1920","height":"835","rate":""},
			{"imgName":"扎尕那一景.jpg","title":"","description":"","width":"640","height":"960","rate":""},
			{"imgName":"这里不准下水的姑娘.jpg","title":"","description":"","width":"1920","height":"812","rate":""},
			{"imgName":"这是一位在纳木错成长的姑娘.jpg","title":"","description":"","width":"1920","height":"1272","rate":""},
			{"imgName":"只缘身在此山中.jpg","title":"","description":"","width":"662","height":"960","rate":""},
			{"imgName":"住在这里一定很幸福吧.jpg","title":"","description":"","width":"1920","height":"1280","rate":""}
		]
	}
];